### ISSUE TITLE
Note about citing clue.io

### ISSUE THREAD

**Issue by shntnu** [broadinstitute/lincs-cell-painting#1]
We concluded that it is ok to have Level 3-5 data on GitHub, although we will cite clue.io as the primary source and references for this data, similar to this [README](https://github.com/gwaygenomics/cell-health/blob/090b973688c55d6ea216e71f1bb828082d7348de/5.validate-repurposing/data/README.md) by @gwaygenomics 

The following data will eventually be made available on clue.io/morphology

Level 1-5 + connectivity file of
- REP (1571 compounds, A549, 48h, 6 doses)
- LKCP (~360 compounds, MCF7/A549/U2OS, 6h/24h/48h, 3 doses)
- DBG (a subset of LKCP)

**Comment by gwaygenomics** [comment]
Can I clarify what the different data levels are? Is this accurate?

| Data | Level |
| :---- | :---- |
| Images | Level 1 |
| SQLite File (single cell profiles ) | Level 2 |
| Aggregated Profiles with Well Information (metadata) | Level 3 |
| Normalized Aggregated Profiles with Metadata | Level 4 |
| Normalized and Feature Selected Aggregated Profiles with Metadata | Level 5 |

**Comment by shntnu** [comment]
> Can I clarify what the different data levels are? Is this accurate?

I have updated your table @gwaygenomics
