### ISSUE TITLE
Add conda environment

### ISSUE THREAD

**Issue by gwaygenomics** [broadinstitute/lincs-cell-painting#15]
Ideally, I should have added a conda environment (and setup instructions) in #7 - but alas, I didn't!

In #13 @niranjchandrasekaran introduced `rdkit` as a dependency (this has inspired the creation of this issue). It looks like [it does exist in conda-forge](https://anaconda.org/conda-forge/rdkit) so it should not be a problem.

@niranjchandrasekaran - what version did you use?

**Comment by niranjchandrasekaran** [comment]
It's `2019.09.03`

```
import rdkit
print(rdkit.__version__)
2019.09.3
```
