### ISSUE TITLE
Updated Strategy for Adding Profiles

### ISSUE THREAD

**Issue by gwaygenomics** [broadinstitute/lincs-cell-painting#22]
At the profiling checkin today, we discussed our strategy to adding (and evaluating) profiles in this project.

This issue supersedes #4 

1. I will complete #21 and @niranjchandrasekaran will review
2. We will add median profiles to this repository as a first step
3. I will confirm floating point differences between pycytominer and cytominer processed profiles (note the limitations discussed in https://github.com/broadinstitute/lincs-cell-painting/issues/3#issuecomment-591994451)
4. We will add mean profiles to this repo next
5. We will perform an evaluation of sorts to compare mean vs. median profiles

**Comment by shntnu** [comment]
> 5\. We will perform an evaluation of sorts to compare mean vs. median profiles

The reason for doing this is the issue mentioned in https://github.com/broadinstitute/lincs-cell-painting/issues/4#issuecomment-620978559

**Comment by gwaygenomics** [comment]
closing in favor of project management in https://github.com/broadinstitute/lincs-cell-painting/projects/1 (plus normalization strategy comparison in #39)

**Comment by shntnu** [comment]
> 5\. We will perform an evaluation of sorts to compare mean vs. median profiles

@gwaybio do you have any recollection if we ever compared mean vs. median for Level2->Level 3 in this project?

**Comment by gwaybio** [comment]
@shntnu - not that I can recall, I don't think we did
