### ISSUE TITLE
Define folder structure 

### ISSUE THREAD

**Issue by shntnu** [broadinstitute/lincs-cell-painting#23]
@gwaygenomics it might be useful to define the folder structure of the data

Here's what I am thinking https://github.com/cytomining/profiling-handbook/issues/54#issue-610880499 but feel free to propose alternatives. 

[This](https://cytomining.github.io/profiling-handbook/appendix-a.html#project-folder-structure-guidance) was our thinking when we defined the folder structure (transcribed by @gwaygenomics)

**Comment by gwaygenomics** [comment]
:+1: let's do it! I currently have all of the pycytominer-derived profiles in a `backend` folder within `profiles`. (i.e. `profiles/backend/`) I didn't add `batch` info to this, but we very easily can.

I think it is worth adding to keep consistent with our traditional conventions.

We also have a `metadata/platemaps` folder without `batch` info. We can add this as well.

One differences is in the `profiles/results` directory where we have cell counts per well saved.

**Comment by shntnu** [comment]
Great – lets continue the discussion in https://github.com/cytomining/profiling-handbook/issues/54#issue-610880499
