### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by gwaygenomics** [broadinstitute/lincs-cell-painting#27]
@shntnu - we should add an open source license to this repo before adding profiles. Have we thought about which license we should apply here?

**Comment by shntnu** [comment]
We'd need to have separate licenses for code and data.

- The code can be whatever we like; I'd go with MIT or BSD 3?
- The data will have to be whatever clue.io / CMap decides.

(this is a stub)

**Comment by gwaygenomics** [comment]
> We'd need to have separate licenses for code and data.
> The code can be whatever we like; I'd go with MIT or BSD 3?

👍 i like this plan. Let's go with BSD3 for the code.

> The data will have to be whatever clue.io / CMap decides.

Ultimately, I agree here. I do think that we have an opportunity to provide a strong recommendation to the clue/CMAP team to apply a permissive open source license to the data. In addition to the inherent benefit of the data being open to the wider public, we intend to use the data in this repo for a wide variety of our own projects - in other words, we should try to make it freely available to unencumber our future selves! 

Based on a quick glance, it doesn’t look like CLUE has an official license, but they restrict access based on “access keys” (https://clue.io/terms#data). We should avoid this model as it makes usage bulky. Also, it presents a large barrier to end-to-end reproducible workflows that we can mitigate with an open source license.

Perhaps we can use this opportunity for CMAP to test a completely open model with a subset of their lower priority data/goals?
