### ISSUE TITLE
Add consensus perturbation signatures

### ISSUE THREAD

**Issue by gwaygenomics** [broadinstitute/lincs-cell-painting#36]
My current plan is as follows:

- [x] 1. Process each plate independently (✅ in #34)
- [x] 2. Generate an across-plate consensus signature on broad_sample and dose.
- [x] 3. The consensus signature will be based on `median` and `MODZ`
- [x] 4. Output one single file for the full consensus signature
- [ ] 5. Output a separate file for a feature selected consensus signature (derived after calculating consensus)

Unifying documentation for this step from https://github.com/broadinstitute/lincs-cell-painting/issues/4#issuecomment-620839509 and https://github.com/broadinstitute/lincs-cell-painting/pull/34#issuecomment-629307961

**Comment by shntnu** [comment]
> * [ ]  5. Output a separate file for a feature selected consensus signature (derived after calculating consensus)

You would not be able to do `replicate_correlation` selection on consensus profiles. You'd need to do this on the Level 4b data across all plates instead. But also note that when we do so, we first [sample](https://github.com/cytomining/profiling-handbook/blob/master/06-create-profiles.Rmd#L371-L378) a subset of the plates to avoid inflating the report replicate correlations.

I'd skip 5. for now unless it is blocking

**Comment by gwaygenomics** [comment]
closed in #40
