### ISSUE TITLE
Create connectivities matrix

### ISSUE THREAD

**Issue by shntnu** [broadinstitute/lincs-cell-painting#46]
Create 1571x1571 matrix of connectivities between compounds. Details tbd.

**Comment by shntnu** [comment]
- [ ] create write_gct.R in cytotools so that we can convert CSV to GCT
- [ ] create GCT version of [2016_04_01_a549_48hr_batch1_consensus_modz.csv.gz](https://github.com/broadinstitute/lincs-cell-painting/blob/master/consensus/2016_04_01_a549_48hr_batch1/2016_04_01_a549_48hr_batch1_consensus_modz.csv.gz)
- [ ] Run [cmapM](https://github.com/cmap/cmapM) scripts to generate introspect matrix
- [ ] Run [cmapM](https://github.com/cmap/cmapM) scripts to generate aggregated matrix

**Comment by gwaygenomics** [comment]
Noting [`pycytominer.write_gct()`](https://github.com/cytomining/pycytominer/blob/master/pycytominer/write_gct.py) here in case it is at all helpful

**Comment by shntnu** [comment]
We decided not to drop the View Connectivities link in clue.io/morphology given the overhead required for creating that file. We will instead make the `consensus/2016_04_01_a549_48hr_batch1/2016_04_01_a549_48hr_batch1_consensus_modz.csv.gz` available as a GCT file that can be directly loaded in morpheus.
