### ISSUE TITLE
Consensus profiles are missing MOA and target information

### ISSUE THREAD

**Issue by shntnu** [broadinstitute/lincs-cell-painting#49]
@gwaygenomics Were MOA and target columns left out intentionally?

https://github.com/broadinstitute/lincs-cell-painting/blob/e6852b49992b4fa2f0d36cc07011856ebee6326a/consensus/scripts/nbconverted/build-consensus-signatures.py#L152-L158

These columns are not present

```
Metadata_moa
Metadata_target
```

and other cool stuff you'd find in `*_augmented.csv" files

**Comment by gwaygenomics** [comment]
>  Were MOA and target columns left out intentionally?

Nope, not intentional. Let's add them back

**Comment by gwaygenomics** [comment]
fixed in #63
