### ISSUE TITLE
Add --no-name gzip flag to compression file output

### ISSUE THREAD

**Issue by gwaygenomics** [broadinstitute/lincs-cell-painting#50]
We are get annoying file diff triggers when reprocessing the pipeline, even if nothing changes in the file. This is important to fix so that we are able to isolate _actual_ changes that result from reprocessing output data.

As @shntnu notes in #48 the reason why the gzip files are triggering positive diffs, is because of an added timestamp.

The way to remove the timestamp from the file is to pass a `--no-name` (`-n`) flag to the gzip command. See http://linuxcommand.org/lc3_man_pages/gzip1.html

Fortunately, it looks like pandas-dev/pandas#33398 has added the ability to include args to pandas `gzip` compression. This improvement will be included in [pandas version 1.1](https://github.com/pandas-dev/pandas/milestone/68), which is scheduled for an Aug 1 release.

## Three Options

* pandas v1.1 option (assuming that it solves this problem!)
* base python option (outlined https://github.com/broadinstitute/lincs-cell-painting/pull/48#issuecomment-636462269)
* bash option (outlined https://github.com/broadinstitute/lincs-cell-painting/pull/48#issuecomment-636337076).

For the pandas or python option, the solution should ideally live in `pycytominer`. I've created a stub for this at cytomining/pycytominer#83

**Comment by gwaygenomics** [comment]
fixed in #63

**Comment by shntnu** [comment]
Awesome!!!
