### ISSUE TITLE
Second batch of lincs data

### ISSUE THREAD

**Issue by gwaygenomics** [broadinstitute/lincs-cell-painting#57]
@shntnu - I remember you mentioning that we have another batch of Cell Painting data for this project. Can you point me to where this data lives?

We should work towards getting this data on here and processed. @sMyn42 is looking for a good dataset to test different batch effect correction tools (e.g. Harmony) to extend his Summer Research project. Having the second batch on here will help!

**Comment by shntnu** [comment]
The backends are at https://imaging-platform-cold.s3.us-east-1.amazonaws.com/imaging_analysis/2015_10_05_DrugRepurposing_AravindSubramanian_GolubLab_Broad/plates/2015_10_05_DrugRepurposing_AravindSubramanian_GolubLab_Broad_2017_12_05_Batch2_*_backend.tar.gz

Here's how you'd restore them
https://github.com/broadinstitute/imaging-backup-scripts/blob/master/glacier_restore.md

Here's the description of this data set
https://docs.google.com/document/d/1KA4j_grc1uxkCdhCzqEQSps8MGZf9NT7V_F8mmEwPGw/edit

**Comment by gwaygenomics** [comment]
PROJECT_NAME=2015_10_05_DrugRepurposing_AravindSubramanian_GolubLab_Broad
BATCH_ID=2017_12_05_Batch2

**Comment by gwaygenomics** [comment]
[list_of_plates.txt](https://github.com/broadinstitute/lincs-cell-painting/files/5798016/list_of_plates.txt)

**Comment by gwaygenomics** [comment]
batch 2 sqlite files now available internally at /home/ubuntu/bucket/projects/2015_10_05_DrugRepurposing_AravindSubramanian_GolubLab_Broad/workspace/backend/2017_12_05_Batch2

**Comment by gwaygenomics** [comment]
I added batch 2 data in #58 - We can also perform some sort of check, a quick dataset description, and add the results to https://github.com/broadinstitute/lincs-cell-painting/tree/master/comparison

**Comment by sMyn42** [comment]
Cool! I'm planning to get back at it this weekend.

**Comment by gwaygenomics** [comment]
#58 only contains well profiles (levels 2-4b) - We also need to create consensus signatures (level 5) for batch 2 data

**Comment by gwaygenomics** [comment]
Creating batch 2 consensus signatures in #61

**Comment by gwaygenomics** [comment]
the second batch of LINCS data lacks several MOA/Target annotations in our existing metadata map.

We're troubleshooting this in https://github.com/broadinstitute/lincs-cell-painting/issues/62#issuecomment-812184977

**Comment by gwaygenomics** [comment]
I just started running the full profiling pipeline on both batches of data

**Comment by gwaygenomics** [comment]
full pipeline is complete, and now frozen, after merging #63
