### ISSUE TITLE
Two discrepancies in MOA `pert_iname` between samples and drugs files

### ISSUE THREAD

**Issue by gwaygenomics** [broadinstitute/lincs-cell-painting#6]
I am working on step 4 of https://github.com/broadinstitute/lincs-cell-painting/issues/5#issuecomment-600208689 and came across two discrepancies between the `samples` and `drugs` files. They are likely very minor, and can easily be resolved, but I am noting them here for completeness.

 When comparing `pert_iname` between the two files (drugs and samples),  every single `pert_iname` entry in the drugs file is found in the samples file. However, two `pert_iname`  entries are found in the samples file and not in the drugs file.

The two `pert_iname` entries are:

1. `YM-298198-desmethyl`
2. `golgicide-A`

## Reconciliation of `YM-298198-desmethyl`

The compound `YM-298198-desmethyl` is missing from the `drugs` file, but the entry `YM-298198`.
[`YM-298198-desmethyl`](https://www.tocris.com/products/desmethyl-ym-298198_2447) is a derivative of [`YM-298198`](https://www.tocris.com/products/ym-298198-hydrochloride_2448), and therefore has a different structure. 

### Samples File

![image](https://user-images.githubusercontent.com/7340421/77200909-e7e50600-6ac1-11ea-8c14-c692b29be752.png)

### Drugs File

![image](https://user-images.githubusercontent.com/7340421/77200940-fc290300-6ac1-11ea-9387-8b51f8903891.png)

### Conclusion

I think it is safe to duplicate the `YM-298198` drug column and make one `pert_iname` entry `YM-298198-desmethyl`.

## Reconciliation of `golgicide-A`

This appears to be, simply, an issue of capitalization. See below:

### Samples File

Note the exact same `smiles` string, but different `broad_ids` (b/c of different purities and vendors).

![image](https://user-images.githubusercontent.com/7340421/77201382-c59fb800-6ac2-11ea-8e94-8d712632c401.png)

### Drugs File

![image](https://user-images.githubusercontent.com/7340421/77201454-e10ac300-6ac2-11ea-9f69-2a59589103c4.png)

### Conclusion

I will rename the first entry in the samples file for `BRD-A57886255-001-02-9` to have a lower-case `golgicide-A`.

## Summary

Two `pert_iname` entries had conflicts. The proposed solutions will remedy. Note that I will include the jupyter notebook that performs this adjustment in the repo.

**Comment by gwaygenomics** [comment]
cc @niranjchandrasekaran @shntnu - in case either of you have run into this issue and solved it before

**Comment by niranjchandrasekaran** [comment]
Thanks @gwaygenomics for figuring this out! It will be helpful when I am losing my mind over why the lists aren't matching.

On a side note: Usually, I merge the two lists (`samples` and `drugs`) using `InChIKey`. When Shantanu and I did that, we ran into another issue where there were multiple `pert_iname` mapping to the same `InChIKey` and `InChIKey` and `smiles` did not match 1:1. We have taken [this approach](https://github.com/broadinstitute/jump-cellpainting/pull/14#issuecomment-568015892) to overcome the problems and the cleaned up `samples` file is [here](https://github.com/broadinstitute/jump-cellpainting/blob/master/0.design-pilots/output/repurposing_samples_20180907_vendor_availability_cleaned.csv).  This file also contains additional vendor availability information, which may not be useful to you.

**Comment by gwaygenomics** [comment]
oh interesting! Thanks for sharing @niranjchandrasekaran.

Where are you retrieving the `drug` file from? On the repurposing homepage in CLUE (https://clue.io/repurposing) the `drug` file does not have an `InChIKey` column.

This is the source of data in this repo (https://github.com/broadinstitute/lincs-cell-painting/issues/5#issuecomment-601863188) - maybe it is different in JUMP?

**Comment by niranjchandrasekaran** [comment]
Ah you are right; I take that back. There I no `InChIKey` in the drug file and I have been using `pert_iname` to merge the two lists. This means, I have not been annotating these two compounds with their respective MOAs/targets. Thanks for bringing this to my attention.

**Comment by gwaygenomics** [comment]
no longer an issue. Solved specifically in https://github.com/broadinstitute/lincs-cell-painting/issues/8#issuecomment-606572661 and implemented in #7
