### ISSUE TITLE
Finalizing authors

### ISSUE THREAD

**Issue by gwaygenomics** [broadinstitute/lincs-cell-painting#67]
We need to finalize authors for the version 1 release of this repository.

The authors should be those involved in the LINCS Cell Painting data creation. This means individuals involved in:

- funding acquisition
- experiment planning
- assay optimization
- data collection
- data processing
- data curation

I know that this is a complex task, but its complexity matches its importance. Once we define authors we can ensure proper  attribution to all papers that use this data. @shntnu - please help me with this :)

Once we define authors, I will also:

- [x] Update the zenodo archive https://zenodo.org/record/3928744#.YLTxBpNKiQ4 (I'll also update this to version 1)
- [ ] Mark this task as complete in the LINCS complementarity paper

**Comment by shntnu** [comment]
I've pinged Ted [here](https://docs.google.com/document/d/1AK2SaqG_Pd9h3erFcufzQSzInLrWeGx6aS20RFDL3AA/edit?disco=AAAAMeSK9Ls)

**Comment by gwaygenomics** [comment]
It sounds like this has been resolved. @shntnu - I am going to get to this this afternoon. Is that google doc also reflective of author order? IMO, you can make that call initially, let Ted know, and then we can always change it if need be.

**Comment by shntnu** [comment]
Ted Natoli, Gregory P. Way, Xiaodong Lu, David Logan, Maria Alimova, Kate Hartland, Todd Golub, Anne E. Carpenter, Shantanu Singh, Aravind Subramanian
