### ISSUE TITLE
Broad ID to MOA Discrepancy

### ISSUE THREAD

**Issue by wongdanr** [broadinstitute/lincs-cell-painting#83]
Hello @gwaygenomics 
I noticed that there is a discrepancy on some mappings from Broad ID to MOA. 
For instance in repurposing_info_long.tsv, the Broad ID: BRD-K66035042-001-10-1 maps to the MOA: mucolytic agent.
While in repurposing_info_external_moa_map_resolved.tsv, the same Broad ID maps to the MOA: diuretic. Which .tsv file is correct? Thank you!

**Comment by gwaygenomics** [comment]
We curated all CLUE metadata versions and, IIRC (details are in this repo), we used the latest version if there were ID collisions. Can you check if this explains the discrepancy?

**Comment by wongdanr** [comment]
I see, in this script line 545: [https://github.com/broadinstitute/lincs-cell-painting/blob/f865c796757326dcc377e30dc5b11b5ae392a98b/metadata/moa/scripts/nbconverted/3.align-moa.py#L545](url) I interpret this as saying that repurposing_info_external_moa_map_resolved.tsv is the most recent and up to date, is this true? Thanks!
