### ISSUE TITLE
Make single cell .SQLite files publicly available

### ISSUE THREAD

**Issue by gwaybio** [broadinstitute/lincs-cell-painting#84]
We'd ideally like to make all single cell SQLite files publicly available. As @shntnu noted to me in a separate email, the lab has a process in place to accomplish this, which is great!

To summarize the plan that @shntnu outlined:

## Step 1: Make SQLite files available via [RODA](https://registry.opendata.aws/)

However, this step has two blocking tasks:

- @shntnu is blocking this PR https://github.com/awslabs/open-data-registry/pull/1003#issuecomment-957363361
  - Which in turn is blocked by @shntnu / @ErinWeisbart on https://github.com/broadinstitute/cellpainting-gallery/issues/1

## Step 2: Unarchive SQLite files

The big lift here is unarchiving the data

### Unarchiving notes: 

- Previously performed in https://github.com/broadinstitute/lincs-cell-painting/issues/57#issuecomment-764003769 using instructions in https://github.com/broadinstitute/lincs-cell-painting/issues/57#issuecomment-757392154.

## Step 3: Copy SQLite files

All we need to do here is copy the unarchived SQLite to s3://cellpainting-gallery/cpg0004-lincs/broad/workspace/backend/${batch}.

**Comment by gwaygenomics** [comment]
@shntnu please post if you have already thought through any strategy on how to accomplish this! Thanks!

**Comment by gwaygenomics** [comment]
Got it! Yes, this is helpful to document here.  

> However, if there's anyone on your team who is able and willing, we can provide them AWS credentials to do this task.

Unfortunately, there is no such person at the moment. The rotating students are wrapping up their rotation, and hiring has still be tough. If you're not able to find an author on the paper, LMK and I can try myself.

**Comment by shntnu** [comment]
> If you're not able to find an author on the paper, LMK and I can try myself.

Will do

Do you have any specific timeline in mind?

**Comment by gwaygenomics** [comment]
Ideally sometime before the paper is published. I don't know how long that will take.

I'm also proposing to use the single cell data in a separate proposal, that I'd love to have by mid-September.

So let's say 4 months to a live AWS link?

**Comment by shntnu** [comment]
Tagging @echterobert because this is relevant to his project

**Comment by EchteRobert** [comment]
Something happened to my AWS account, so I've asked BITS to help me out with that. As soon as that is fixed I can start working on step 2.

I'm relatively new to AWS so just to make sure I understand correctly, I simply need to: 

Retrieve the data from glacier here: 
https://imaging-platform-cold.s3.us-east-1.amazonaws.com/imaging_analysis/2015_10_05_DrugRepurposing_AravindSubramanian_GolubLab_Broad/plates/2015_10_05_DrugRepurposing_AravindSubramanian_GolubLab_Broad_2017_12_05_Batch2_${BATCH_ID}_backend.tar.gz 
to an accessible bucket here: 
s3://imaging-platform/projects/2015_10_05_DrugRepurposing_AravindSubramanian_GolubLab_Broad/workspace/backend/${BATCH_ID}/
using an EC2 instance as described here:
https://github.com/broadinstitute/imaging-backup-scripts/blob/master/glacier_restore.md 

And in step 3 we then copy the data from the imaging-platform bucket to the cellpainting gallery.

**Comment by shntnu** [comment]
@EchteRobert That's exactly right! I'd recommend using #ip-it Slack so you can get quick help from others in the group in case you are stuck

**Comment by shntnu** [comment]
@EchteRobert send me his bash notes

<details>

```sh
sudo su

mkdir ~/ebs_tmp/

cd ~/ebs_tmp

sudo yum install git -y

sudo amazon-linux-extras install epel

sudo yum install nload sysstat parallel -y

git clone https://github.com/broadinstitute/imaging-backup-scripts.git

aws configure
# enter credentials

cd imaging-backup-scripts

PROJECT_NAME=2015_10_05_DrugRepurposing_AravindSubramanian_GolubLab_Broad
BATCH_ID=2016_04_01_a549_48hr_batch1

parallel \
	--results restore \
	-a ../list_of_plates.txt \
	./glacier_restore.sh \
	--project_name ${PROJECT_NAME} \
	--batch_id ${BATCH_ID} \
	--plate_id {1} \
	--get_backend

parallel \
	--results restore \
	-a ../list_of_plates.txt \
	./glacier_restore.sh \
	--project_name ${PROJECT_NAME} \
	--batch_id ${BATCH_ID} \
	--plate_id {1} \
	--get_backend \
	--check_status


cd ~/ebs_tmp

parallel -a list_of_plates.txt "grep ^Download imaging-backup-scripts/restore/1/{1}/stdout|sed s,Download:,,1" > url_list.txt # done
parallel -a list_of_plates.txt "grep MD5Download imaging-backup-scripts/restore/1/{1}/stdout|sed s,MD5Download:,,1" > md5_url_list.txt # done

parallel -a url_list.txt aws s3 cp {1} . # done
parallel -a md5_url_list.txt aws s3 cp {1} . # done

PROJECT_NAME=2015_10_05_DrugRepurposing_AravindSubramanian_GolubLab_Broad
BATCH_ID=2016_04_01_a549_48hr_batch1
TARSET=backend

parallel -a list_of_plates.txt tar -xvzf ${PROJECT_NAME}_${BATCH_ID}_{1}_${TARSET}.tar.gz

parallel -a list_of_plates.txt \
  "md5sum ${PROJECT_NAME}_${BATCH_ID}_{1}_${TARSET}.tar.gz > ${PROJECT_NAME}_${BATCH_ID}_{1}_${TARSET}.md5.local"

parallel -a list_of_plates.txt \
  diff \
  ${PROJECT_NAME}_${BATCH_ID}_{1}_${TARSET}.md5.local \
  ${PROJECT_NAME}_${BATCH_ID}_{1}_${TARSET}.md5 > md5_diffs.txt

```

</details>

**Comment by shntnu** [comment]
I'm now upload all the contents of `backend` to ` s3://cellpainting-gallery/cpg0004-lincs/broad/workspace/backend/`

After uploading, I will delete everything except <PLATE>.csv and <PLATE>.sqlite from S3

```
.
└── 2016_04_01_a549_48hr_batch1
    ├── SQ00014812
    │   ├── SQ00014812_augmented.csv
    │   ├── SQ00014812.csv
    │   ├── SQ00014812_normalized.csv
    │   ├── SQ00014812_normalized_variable_selected.csv
    │   ├── SQ00014812_normalized_variable_selected.gct
    │   └── SQ00014812.sqlite
...
```

**Comment by shntnu** [comment]
Done!

**Comment by gwaybio** [comment]
Yes!!! Thanks so much for the work on this @shntnu and @EchteRobert 🎉🎉

**Comment by EchteRobert** [comment]
Awesome!
